name: striprft build
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6,3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -r crawler/requirements.txt
        python -m pip install -r web/requirements.txt
        python -m pip install -r receiver/requirements.txt
    - name: run tests
      run: python -m pytest
